{
 "title": "E通效能指标Dashboard",
 "description": "E通效能指标Dashboard",
 "time": { "from": "now-14d", "to": "now" },
 "panels": [
  {
   "title": "代码质量（Sonar扫描结果）",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Sonar风险个数（致命和严重）",
   "type": "timeseries",
   "description": "Sonar风险个数（致命和严重）",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n    STR_TO_DATE(\n        DATE_FORMAT(DATE, '%Y-%m-%d'),\n        '%Y-%m-%d %H:%i:%S'\n    ) as '日期',\n    count AS '数量'\nFROM\n    risk"
    }
   ]
  },
  {
   "title": "  测试覆盖率",
   "type": "timeseries",
   "description": "  测试覆盖率",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n    STR_TO_DATE(\n        DATE_FORMAT(DATE, '%Y-%m-%d'),\n        '%Y-%m-%d %H:%i:%S'\n    ) as '日期',\n    coverage AS '覆盖率'\nFROM\n    test_coverage"
    }
   ]
  },
  { "title": "BUG统计", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "BUG数量变化趋势（致命和严重）",
   "type": "timeseries",
   "description": "致命和严重的BUG数量变化趋势",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n    r1.theDate AS '日期',\n    r1.bugCount AS '致命BUG数量',\n    r2.bugCount AS '严重BUG数量'\nFROM\n    (\n    SELECT\n        STR_TO_DATE(\n            DATE_FORMAT(start_time, '%Y-%m-%d'),\n            '%Y-%m-%d %H:%i:%S'\n        ) AS theDate,\n        COUNT(*) AS bugCount\n    FROM\n        bug_info bi\n    LEFT JOIN bug_level bl ON\n        bi.level_id = bl.id\n    WHERE\n        bl.id = 1\n    GROUP BY\n        STR_TO_DATE(\n            DATE_FORMAT(start_time, '%Y-%m-%d'),\n            '%Y-%m-%d %H:%i:%S'\n        )\n) r1\nJOIN(\n    SELECT\n        STR_TO_DATE(\n            DATE_FORMAT(start_time, '%Y-%m-%d'),\n            '%Y-%m-%d %H:%i:%S'\n        ) AS theDate,\n        COUNT(*) AS bugCount\n    FROM\n        bug_info bi\n    LEFT JOIN bug_level bl ON\n        bi.level_id = bl.id\n    WHERE\n        bl.id = 2\n    GROUP BY\n        STR_TO_DATE(\n            DATE_FORMAT(start_time, '%Y-%m-%d'),\n            '%Y-%m-%d %H:%i:%S'\n        )\n) r2\nON\n    r1.theDate = r2.theDate"
    }
   ]
  },
  {
   "title": "BUG原因和数量（过去两周）",
   "type": "barchart",
   "description": "BUG原因和数量（过去两周）",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n    br.description AS '原因',\n    COUNT(*) AS '数量'\nFROM\n    bug_info bi\nLEFT JOIN bug_reason br ON\n    bi.reason_id = br.id\nWHERE\n    bi.start_time > DATE_SUB(NOW(), INTERVAL 2 WEEK)\nGROUP BY\n    br.id,\n    br.description\nORDER BY\n    COUNT(*)\nDESC\n    "
    }
   ]
  },
  {
   "title": "BUG严重等级和数量（过去两周）",
   "type": "barchart",
   "description": "BUG严重等级和数量（过去两周）",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n    bl.description AS '等级',\n    COUNT(*) AS '数量'\nFROM\n    bug_info bi\nLEFT JOIN bug_level bl ON\n    bi.level_id = bl.id\nWHERE\n    bi.start_time > DATE_SUB(NOW(), INTERVAL 2 WEEK)\nGROUP BY\n    bl.id,\n    bl.description"
    }
   ]
  }
 ]
}